config/routes.rb
Saladx::Application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users, path: 'cooks', as: 'cooks', controller: 'cooks/cooks' do
    resources :orders, controller: 'cooks/orders', defaults: { format: :json } do
      collection do
        get 'next'
      end
      member do
        post 'complete'
      end
    end
  end

  resources :orders do
    member do
      get 'thank_you'
    end
  end

  root to: 'orders#new'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  scope :greens, -> { where(category: 'greens') }
  scope :vegetables, -> { where(category: 'vegetables') }
  scope :proteins, -> { where(category: 'protein') }
  scope :available, -> { where('available_servings > 0') }

  before_create :generate_label
  #need to convert nutrients based on serving_size ratio to whatever the nutrient definition amount is

  def self.categories
    uniq.pluck(:category)
  end

  def generate_label
    last_label = self.class.where(category: category).order(:label).last.try(:label) || "X0"
    last_label_number = last_label.scan(/\d+/).first.to_i
    self.label = "#{category.first.upcase}#{last_label_number+1}"
  end

  def as_json(options={})
    attributes.with_indifferent_access.slice(:name, :label)
  end

  def to_nutrition
    to_select_nutrition(:all)
  end

  def to_important_nutrition
    to_select_nutrition(:important)
  end

  def nutrition_facts
    @nutrition_facts ||= begin
      active_nutrient = ActiveNutrition.search(self.name).first
      active_nutrient.present? ? active_nutrient.nutrition_facts.to_hash(by: :nutrition_number) : {}
    end
  end

  def nutrients
    Rails.cache.fetch(['v4', name, 'nutrients', updated_at]) do
      nn = Nutrient.where(Nutr_No: nutrition_facts.keys)
      nn.any? ? nn.each {|n| n.amount = nutrition_facts[n.Nutr_No]; n } : []
    end
  end

  alias_method :all_nutrients, :nutrients

  def important_nutrients
    nutrients.select{ |nutrient| nutrient.importance > Nutrient::IMPORTANCE_LOWER_BOUND }
  end

  private
  def to_select_nutrition(which=:all)
    {
      self.id => send("#{which}_nutrients").reduce({}){ |h, nutrient| nutrient && (h[nutrient.name] = {amount: nutrient.amount, pdv: nutrient.pdv}); h }
    }
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :orders

  accepts_nested_attributes_for :recipe_ingredients

  def as_json(options={})
    attributes.with_indifferent_access.slice(:name).merge(recipe_ingredients: recipe_ingredients.map(&:as_json))
  end
end

app/views/ingredients/_ingredients.html.slim
.bs-callout.bs-callout-thick.col-md-12 class="bs-callout" id=category style="border-left-color: ##{hexcolor(category)}"
  h4 = t("categories.#{category}.title")
  - ingredients.each_slice(5) do |column_ingredients|
    .col-md-6
      = r.input :ingredient_ids, as: :check_boxes, collection: column_ingredients, label_method: :name, label: false, required: false, wrapper_html: { class: 'choose-ingredients' }, hidden_fields: false, value_as_class: true
      / ins.iCheck-helper

      / label class="icheckbox_flat-green checked"
      /   input class="icheck" type="checkbox" name="check3" style="position: absolute; opacity: 0;"